version: '3.8'

services:
    api:
        image: unisys-rs/api
        container_name: unisys-rs.api
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
          - ./volumes:/mnt/volumes
          - ./unisys.db:/mnt/db
